include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_constructors_first: true
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"